# Generated by Django 3.2.20 on 2023-07-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
