# Generated by Django 3.2.20 on 2023-07-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisements_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='auction_test',
        ),
    ]
