# Generated by Django 3.2.20 on 2023-07-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_remove_advertisements_auction_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cats',
        ),
    ]
