# Generated by Django 3.2.20 on 2023-08-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0008_cats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisements',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
