# Generated by Django 4.2.2 on 2023-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advetrisements/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
