# Generated by Django 3.2.20 on 2023-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Орк', 'Орк'), ('Фурри', 'Фурри'), ('Spider man', 'Spider man')], default='Орк', max_length=50)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
