# Generated by Django 3.2.20 on 2023-07-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='add',
        ),
    ]
